### ISSUE TITLE
External Rook storage cluster

### ISSUE THREAD

**Issue by emedina** [crossplane/tbs#1]
It would be fantastic to be able to run one or more independent clusters of Rook in K8s, and still be able to mount volumes using such storage in other K8s clusters.

So for example, I could create a K8s cluster only with storage servers, then deploy Rook on top of it and expose somehow all its storage to other applications running in other k8s clusters.

**Comment by jbw976** [comment]
Hi @emedina, thank you for writing up your idea!

Were you hoping for Crossplane to help orchestrate the deployment of a multi-cluster Rook setup?  If so, do you mind if we transfer this issue over to the main crossplane repo?

This `tbs` repo is for a new live streaming show that we're starting called [The Binding Status](https://github.com/crossplaneio/tbs/blob/master/README.md), so the main crossplane repo is a better home for features and improvements you'd like to see in Crossplane :)

**Comment by emedina** [comment]
Ah, ok, I thought this was somehow already possible...

**Comment by emedina** [comment]
https://github.com/crossplaneio/crossplane/issues/365
